In [1]:
import numpy as np

### FUNCTIONS ###



# CREATE MATRIX LABELS
def create_labels(M):
    
    # STORE THE DIMENSIONS OF THE MATRIX
    row_size,col_size = M.shape
    
    r = ["X"+str(i+1) for i in range(col_size)]
    c = ["Y"+str(i+1) for i in range(row_size)]
    
    r[-1] = c[-1] = "-1"
    
    # RETURNS A TUPLE WITH LABELS[0] BEING THE LABELS FOR COLUMNS AND LABELS[1] FOR ROWS
    return (r,c)


# CREATE A FUNCTION THAT TAKES AS INPUT A TABLEAU,
# AND OUTPUT A FEASIBLE PIVOT ROW AND COLUMN
# (STEP 3-6 FOR SIMPLEX METHOD)
# (IF THERE IS NO FEASIBLE ROW, 
# THEN THE OUTPUT SHOULD INDICATE IT) 
def findPivot(M):
    
    # STORE THE DIMENSIONS OF THE MATRIX
    row_size,col_size = M.shape
    
    # ITERATE THROUGH EACH COLUMN, EXCEPT THE LAST ONE
    for col in range(col_size-1):
        
        # CREATE A COLUMN VECTOR
        col_vec = M[:,col]
        
        # CHECKS IF THE ELEMENTS ARE > 0
        # FOR THE EXCEPTION OF THE LAST ELEMENT
        # IF FALSE, THEN LOOP CONTINUES TO ITERATE
        
        if (np.all(col_vec[:-1] > 0)):
        
            # Since the code reached here, it means all the entries 
            # in the col vector are positive for the
            # exception of the last element (if applicable)

            last_col = np.array(M[:,-1])
            
            # RETURNS THE INDEX OF THE MINIMUM VALUE OF THE CALCULATION (ROW PIVOT) AND THE COLUMN PIVOT
            # THE'B' COLUMN DIVIDED BY COLUMN VECTOR  
            return (np.argmin((last_col[:-1]/col_vec[:-1])),col)
    
    return -1
        
    

    
# CREATE A FUNCTION THAT TAKES AS INPUT A TABLEAU,
# AND A GIVEN PIVOT ROW AND COLUMN, AND OUTPUT
# THE PIVOTED TABLEAU
def row_elim(M,labels,rc_index):
    
    print("--------------------------------")
    print("Matrix:")
    print(M)
    print("")
    
    # STORE THE DIMENSIONS OF THE MATRIX
    row_size,col_size = M.shape
    
    # GET THE COLUMN AND ROW PIVOT INDEX
    Mrow,Mcol = rc_index
    
    print("Pivot",rc_index)
    print("")
    
    # GET THE COLUMN VECTOR OF THE PIVOT COLUMN
    M_old_col = np.copy(M[:,Mcol])
    
    print("Col Vec:",M_old_col)
    print("")
    
    # GET THE PIVOT ELEMENT
    pivot = M[Mrow,Mcol]
    
    print("Pivot Val:",pivot)
    print("")
    
    # PIVOT ROW IS DIVIDED BY THE PIVOT
    M[Mrow,:] = M[Mrow,:] / pivot
    
    print("PIVOT ROW IS DIVIDED BY THE PIVOT:")
    print(M)
    print("")
    
    # PERFORM ROW REDUCTION TO EVERY ROW, EXCEPT THE PIVOT ROW
    for i in range(row_size):
        
        # PERFORM ROW REDUCTION TO EVERY ROW, EXCEPT THE PIVOT ROW
        if not(i == Mrow):
            M[i,:] = M[i,:] - M[i,Mcol]*M[Mrow,:]
            
            
    print("PERFORM ROW REDUCTION TO EVERY ROW, EXCEPT THE PIVOT ROW:")
    print(M)
    print("")
    
    # SUBSTITUTES THE CHANGED PIVOT COLUMN WITH THE (- OLD PIVOT COLUMN / PIVOT) 
    M[:,Mcol] = - M_old_col / pivot

    # SUBSTITUTE THE PIVOT ELEMENT WITH (1/PIVOT)
    M[Mrow,Mcol] = 1 / pivot
    
    print("SUBSTITUTES THE CHANGED PIVOT COLUMN WITH THE (- OLD PIVOT COLUMN / PIVOT) ")
    print("SUBSTITUTE THE PIVOT ELEMENT WITH (1/PIVOT)")
    print(M)
    print("")
    
    # INTERCHANGE THE LABELS FROM PIVOT COLUMN WITH PIVOT ROW
    temp = labels[1][Mrow]
    labels[1][Mrow] = labels[0][Mcol]
    labels[0][Mcol] = temp
    

    # RETURN THE PIVOTED TABLEAU AND THE LABELS
    return M,labels

def simplex_method(M):
    
    # A COPY OF THE MATRIX IS NEEDED SINCE WE'LL BE PERFORMING OPERATIONS
    # ON IT THE ITERATIONS BELOW
    curMatrix = np.copy(M)
    
    # CREATE MATRIX LABELS
    labels = create_labels(M)
    
    # IF THERE IS A PERFORM OPERATION, THEN WE MUST NOT SAY THAT THERE IS NO SOLUTION
    # SO, WE WILL USE THIS VARIABLE AS A FLAG
    count = 0
    
    # LOOPS UNTIL PIVOT IS NOT VALID
    # NOT VALID IS DENOTED AS -1
    while True:
        
        # GETS PIVOT COLUMN AND ROW AS A TUPLE
        pivot = findPivot(curMatrix)
        
        # CHECKS IF IT'S VALID
        if(pivot == -1):
            
            # CHECKS IF OPERATIONS WERE DONE WITH THE MATRIX
            if(count >=1):
                print("Col Label",labels[0])
                print("Row Label",labels[1])
                print("")
                print(curMatrix)
            
            # TELL USER THERE IS NO SOLUTION
            else:
                print("*Maximum problem has unbounded solution.*")
                print("*Minimum problem has no feasible solution.*")
            # END THE LOOP
            break

        else:
            # OPERATIONS DONE
            count+=1
            # PERFORM OPERATIONS
            curMatrix,labels = row_elim(M,labels,pivot)
            

### Section 5 Exercise 5
Use the simplex method to solve Exercise 5 of Section 3
$M_A = \begin{pmatrix} 1&1&200 \\ 1&4&320 \\ 10&20&2200 \\ 40&60&0 \end{pmatrix}$  

In [2]:
M = np.array([[1.0,1.0,200],[1.0,4.0,320.0],[10.0,20.0,2200.0],[40.0,60.0,0.0]])

simplex_method(M)

--------------------------------
Matrix:
[[1.0e+00 1.0e+00 2.0e+02]
 [1.0e+00 4.0e+00 3.2e+02]
 [1.0e+01 2.0e+01 2.2e+03]
 [4.0e+01 6.0e+01 0.0e+00]]

Pivot (0, 0)

Col Vec: [ 1.  1. 10. 40.]

Pivot Val: 1.0

PIVOT ROW IS DIVIDED BY THE PIVOT:
[[1.0e+00 1.0e+00 2.0e+02]
 [1.0e+00 4.0e+00 3.2e+02]
 [1.0e+01 2.0e+01 2.2e+03]
 [4.0e+01 6.0e+01 0.0e+00]]

PERFORM ROW REDUCTION TO EVERY ROW, EXCEPT THE PIVOT ROW:
[[ 1.0e+00  1.0e+00  2.0e+02]
 [ 0.0e+00  3.0e+00  1.2e+02]
 [ 0.0e+00  1.0e+01  2.0e+02]
 [ 0.0e+00  2.0e+01 -8.0e+03]]

SUBSTITUTES THE CHANGED PIVOT COLUMN WITH THE (- OLD PIVOT COLUMN / PIVOT) 
SUBSTITUTE THE PIVOT ELEMENT WITH (1/PIVOT)
[[ 1.0e+00  1.0e+00  2.0e+02]
 [-1.0e+00  3.0e+00  1.2e+02]
 [-1.0e+01  1.0e+01  2.0e+02]
 [-4.0e+01  2.0e+01 -8.0e+03]]

--------------------------------
Matrix:
[[ 1.0e+00  1.0e+00  2.0e+02]
 [-1.0e+00  3.0e+00  1.2e+02]
 [-1.0e+01  1.0e+01  2.0e+02]
 [-4.0e+01  2.0e+01 -8.0e+03]]

Pivot (2, 1)

Col Vec: [ 1.  3. 10. 20.]

Pivot Val: 10.0

PI

Farmer needs to plant $180$ Crop I and $20$ Crop II to generate a Revenue of \\$$8400$